language: node_js
node_js:
- 5.0.0
sudo: false
install:
- npm install
before-deploy:
- npm run build
deploy:
  provider: npm
  email: sampastoriza@yahoo.com
  skip_cleanup: true
  api_key:
    secure: ZPTJNKVGkzorcCntb6fNLKWhOfKjXlcuCkmzyLYh2Afsy8ATDPSP5aKJMxLV3XImQYtwEHaJ98k1DBV89yUJojZw3W6M0+Qo5RNQXCsalyaJkJOcErTDIhblgME8avD9sy6Yr3ZeA5KfNiP7vQktLp395qmXbRLVwcYvhhrlVsTbZUXUhn3k38IqL71laz5gGs94s7ds06LEPlPfp16zGAnylzOo+bF/Cax8ffDl2uNNPsOHa/lSGGV+soISPl0L7aCX6cFcIdVuBUEL+CbjoTmt+iKtBGF/HqvG88Wxge9qJkjGqgGslsnbgs2uWunXDTXl2wBZJaNN3YeuqdWQPl9MS5nXxeWxMZYjxT7bQjDIGhVVmUC+r6so+oSi3sZL+s1OsFSXVzBQmNItDxmqx5K/l60mKbMfta6qnRpLUuT8tnhEsk6F18aai4bchWQXcMSh/iB+fKox90xI+Uy3AHG5iikHsTfmtAFAfWbZk5RIXZpE3gP/z7LqEDgqF7olLBhqM8rRjFHusIVDu0jW+O0wFqaB24bEE3tSc7cURfPaAof2Y+1eLI5vjvsjvdHQ2F5KT3oGG8mL+MOofYQjkJBfiiB3nEqy0rkriNJhXBmZfZud6ICiZlK+jmTfzOVpK7UxZoldKPAj0DFGF7xZ8efoT7hh8RYJ2iS7Bm57fqQ=
  on:
    branch: master
    tags: true